### ISSUE TITLE
RF7 Support

### ISSUE THREAD

**Issue by oianson** [imbus/robotframework-debug#12]
(bringing this over from Slack) .. 
7.0b1 caused a regression in your great debug library due to RF7 removing UserLibrary in [556f6a](https://github.com/robotframework/robotframework/commit/556f6a5514bba73ae39db2d08978ff9860ff6151)

```
(v) OBOEHMER-M-V1ZV:~ oboehmer$ python -m robot.libdoc RobotDebug list
Importing library 'RobotDebug' failed: ImportError: cannot import name 'UserLibrary' from 'robot.running' (/private/tmp/v/lib/python3.9/site-packages/robot/running/__init__.py)
Traceback (most recent call last):
  File "/private/tmp/v/lib/python3.9/site-packages/RobotDebug/__init__.py", line 1, in <module>
    from .RobotDebug import Listener, RobotDebug  # noqa: F401
  File "/private/tmp/v/lib/python3.9/site-packages/RobotDebug/RobotDebug.py", line 8, in <module>
    from .debugcmd import DebugCmd, ReplCmd, is_step_mode
  File "/private/tmp/v/lib/python3.9/site-packages/RobotDebug/debugcmd.py", line 14, in <module>
    from .cmdcompleter import CmdCompleter, KeywordAutoSuggestion
  File "/private/tmp/v/lib/python3.9/site-packages/RobotDebug/cmdcompleter.py", line 13, in <module>
    from .robotkeyword import normalize_kw
  File "/private/tmp/v/lib/python3.9/site-packages/RobotDebug/robotkeyword.py", line 9, in <module>
    from robot.running import TestSuite, UserLibrary
```

**Comment by Snooz82** [comment]
fixed in 4.4.0
